version: '3'
services:
  web:
    image: jmasar
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_JDBCURL: jdbc:postgresql://postgres:5432/jmasar
      SPRING_DATASOURCE_USERNAME: jmasar
      SPRING_DATASOURCE_PASSWORD: jmasar
      DBENGINE: postgresql
      SPRING_PROFILES_ACTIVE: development
      EPICS_CA_ADDR_LIST: 10.0.7.255
  postgres:
    image: postgres:9.6
    ports:
      - "5437:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: jmasar
      POSTGRES_PASSWORD: jmasar
      POSTGRES_DB: jmasar
      PGDATA: /var/lib/postgresql/data/pgdata
